# You can use the static key below for development, or make your own here: https://gchq.github.io/CyberChef/#recipe=Pseudo-Random_Number_Generator(32,'Byte%20array')
# NOTE: DO **NOT** use the key below in any production deployment!
#DANGER_MASTER_KEY = [99,41,244,22,238,93,36,81,71,201,10,206,57,198,233,38,221,50,65,131,199,24,207,12,181,20,47,31,151,23,104,102]

[tokens]
discord = ""

[logging]
important_logs = "https://canary.discord.com/api/webhooks/id/token"
info_logs = "https://canary.discord.com/api/webhooks/id/token"

[database]
postgres="postgres://database?user=user&password=password&host=localhost"

[emoji]
# emoji overrides go here


#Yes = "<:gearYes:459697272326848520>"
#No = "<:gearNo:459697272314265600>"
#Warn = "<:gearWarning:473506219919802388>"
#Info = "<:gearAE:585879894232137739>"
